Require `minitest/mock` since we rely on `stub` in this test file
Otherwise running the test file directly like this:

    $ be ruby -w -Ilib:test test/models/variant_test.rb

Fails with:

    Error:
    ActiveStorage::VariantTest#test_passes_content_type_on_upload:
    NoMethodError: undefined method `stub' for #<ActiveStorage::Service::DiskService:0x00007fd53ba89ef0>
        test/models/variant_test.rb:207:in `block in <class:VariantTest>'