Add missing require to active_storage.rb
Since fc180a9a5041266f6c9db9577e2a8281db0109d5, requiring active_storage
on its own has failed with the following error:

    activestorage/lib/active_storage.rb:55:in `<module:ActiveStorage>': undefined method `minutes' for 5:Integer (NoMethodError)